POST https://localhost:51832/api/gpt/chat
Content-Type: application/json

{"role" : "user", "Message" : "hello gpt"}
###
POST https://localhost:51832/api/gpt/chat
Content-Type: application/json

{"role" : "user", "Message" : "第二个会话"}

