name: BuildAdndTest
on:
  push:
    branches:
      - main
      - feature/*

jobs:
  Init:
    runs-on: ubuntu-latest
    steps:
    - name: PrintName
      env:
        name: "hi dvbb"
      run: |
        echo $name
  Test-Window-2019:
    runs-on: ubuntu-latest
    steps:
    - name: test1
      run: |
        dotnet test
  Test-Linux-2019:
    runs-on: ubuntu-latest
    steps:
    - name: test2
      run: |
        dotnet test


