# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Window2019:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build Solution
      run: |
        eng/scripts/Build-Solutions.ps1
    - name: Run tests
      run: |
        eng/scripts/Test_Solutions.ps1
  UbuntuLatest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install powershell
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list
        sudo apt-get update
        sudo apt-get install -y powershell
    - name: Build Solution
      run: |
        eng/scripts/Build-Solutions.ps1
    - name: Run tests
      run: |
        eng/scripts/Test_Solutions.ps1
  MacOs:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build Solution
      run: |
        eng/scripts/Build-Solutions.ps1
    - name: Run tests
      run: |
        eng/scripts/Test_Solutions.ps1