name: BuildAdndTest
on:
  push:
    branches:
      - main
      - feature/*

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: PrintName
      env:
        name: "hi dvbb"
      run: |
        echo $name
