name: BuildAdndTest
on:
  push:
    branches:
      - main
      - feature/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Project
      run: |
        dotnet build
    - name: Run all unit tests
        needs: job1
      run: |
        dotnet test
