name: BuildAdndTest
on:
  push:
    branches:
      - main
      - feature/*

jobs:
  Init:
    runs-on: ubuntu-latest
    steps:
    - name: PrintName
      env:
        name: "hi dvbb"
      run: |
        echo $name
  Test-Window-2019:
    runs-on: windows-2019
    steps:
    - name: Install dotnet env
      run: |
        winget install Microsoft.DotNet.SDK.6
  Test-Linux-2019:
    runs-on: windows-2019
    steps:
    - name: install dotnet env
      run: |
        winget install Microsoft.DotNet.SDK.6
    - name: build
      run: |
        dotnet build
